--[[
Set NPC idle chat text

This can be achieved by using

{"Text1", "Text2", "Text3",},
to set up a continuous conversation

Note: Do not change the content in [0] = {} below

]]--

local text = {[0] = {1,1},

-- Jokes and Memes
{"Did someone say [Thunderfury, Blessed Blade of the Windseeker]?"},
{"LF healer for Stockades run, must have 5k GS!"},
{"Any portals to Dalaran? I'm stuck in Shattrath again..."},
{"Can someone lend me 1g? I swear I'll pay it back."},
{"Why does everyone keep dying? I said don't stand in the fire!"},
{"Remember the days when Hogger was actually scary?"},
{"BRB bio. Don't pull without me."},
{"Who still farms Anzu for the mount? Just me?"},
{"First time in Karazhan and got lost in the library... classic me."},
{"PUG life chose me. *sigh*"},
{"Why is there always one guy who rolls 'need' on everything?"},
{"When you think you're top DPS... but the tank does more damage."},
{"Do gnomes get height bonuses on mounts? Asking for a friend."},
{"PSA: Loot the dog in Blackrock Spire. It's good luck."},
{"Don't AFK in Stormwind fountain, you might end up dead and naked."},

-- Iconic Moments and Serious Talk
{"LFM for Onyxia, need people who know 'more dots' strategy."},
{"Remember when we all thought Naxxramas was unbeatable?"},
{"That feeling when you finally get Benediction... best day ever."},
{"Anyone else still farming for the Zul'Gurub tiger? Hope dies last."},
{"RIP Southshore, never forget the epic battles of Hillsbrad."},
{"For the Alliance! (unless there's Horde around...)"},
{"Back in my day, you needed 40 people for Molten Core."},
{"Rest in peace to all the lost loot due to random DCs."},
{"Anyone remember the Leeroy Jenkins run? Classic WoW at its finest."},
{"BRB, gotta go turn in my 'Greatfather Winter' quest. Winter Veil season is here!"},

-- Streamer References and Funny Banter
{"As Asmongold would say, 'This is HUGE!' but it's just a green item..."},
{"Echo just cleared Mythic again. Can they be stopped?"},
{"Twitch chat in the game? Don't mind if I do, but keep it classy folks."},
{"This boss is way harder than it looked on Towelliee's stream!"},
{"Where's my wipe counter? I'm giving Max a run for his money here."},
{"I'd donate bits for better RNG at this point."},
{"Can we get a 'gg' in the chat for my death by a murloc?"},
{"Pretty sure Mcconnell would say my DPS is 'not great' right now..."},
{"Saw this strat on Preach's stream. Let's hope it works!"},
{"Jokerd was right... leveling is an art form."},
{"Wiping in raids feels bad, but at least it's free content for the viewers!"},

-- General World Chat and Roleplay
{"Any alchemists here? Need some pots before my next run."},
{"Selling bags! 10 slots, handmade, guaranteed quality!"},
{"LFG Shadowfang Keep, level 18 warrior ready to tank!"},
{"Anyone seen a turtle mount? I swear I just saw one!"},
{"The Scourge invasion event is epic! Has anyone else been farming it?"},
{"Did they nerf mages again? My damage feels off..."},
{"Duel in Goldshire anyone? Loser buys drinks at the Lion's Pride Inn!"},
{"Finally got Exalted with the Argent Dawn. Took long enough..."},
{"Is there an achievement for dying 100 times in one day? If so, I'm close."},
{"Anyone got that new Engineering mount yet? It's a beast."},
{"Just tamed Loque'nahak after 8 hours of camping... worth it!"},
{"Can someone share food? My hunter's pet is starving!"},
{"Doing a mount run. If you want in, come geared!"},
{"LF portal to Ironforge. I'm not walking all the way from Darnassus."},
{"Did they add new hairstyles? My character's due for a change."},
{"For those who seek peace... there's always Northrend fishing."},
{"Who else remembers when the AQ gates opened? The lag was real."},
{"Did anyone else just DC, or is it just my potato internet?"},

-- Multi-line Interactive Chats 2024

{"LFM for Deadmines! Need DPS!", "Count me in, I'm a rogue.", "Same, I can tank if needed."},
{"Did anyone see a random gnome run by in only his underwear?", "Oh no, not him again...", "He's probably on his way to Ironforge to dance on the mailbox."},
{"Anyone selling health potions?", "I’ve got some, what's your offer?", "I’ll trade for mage water!"},
{"What's the hardest raid boss in your opinion?", "I’d say Ragnaros, hands down.", "Nah, Kael'thas with all those adds... brutal."},
{"Where can I find an alchemist?", "I'm in Stormwind if you need flasks or potions.", "Perfect, I'll meet you by the auction house!"},
{"Remember when leveling was actually hard?", "Yeah, those were the days...", "And now people just pay for boosts!"},
{"Is Goldshire safe right now?", "Define 'safe.'", "If you see people dancing on tables... it’s not safe."},
{"Any healers available for Scarlet Monastery?", "I'm a priest. Need some DPS too?", "Yes! Let's do this."},
{"Anyone want to duel?", "Depends, are you one of those 'bubble hearth' paladins?", "I take offense to that... but yes."},
{"What mount are you grinding for?", "The Ashes of Al'ar, it looks amazing!", "Good luck, I've been farming that for months."},
{"LF blacksmith who can craft weapons.", "I can, but mats are hard to get right now.", "I can provide mats if you help me out."},
{"Did you just ninja that item?", "It was an accident, I swear!", "Sure it was... happens every time we get loot."},
{"Anyone doing Stratholme?", "I'm down, need that Baron mount!", "Alright, let’s group up."},
{"How's everyone doing in BGs today?", "Not bad, got three flag caps in Warsong.", "Nice, I’m just trying not to die."},
{"This is my first time in Karazhan!", "Oh, you're in for a treat!", "Don’t forget to talk to Moroes' guests."},
{"I heard there’s a secret vendor in Dalaran?", "Yeah, they sell a pet if you’re Exalted.", "Wait, what pet? I need it!"},
{"Anyone know where the fishing trainer is?", "Check in the capital city, usually by the water.", "Thanks! I’m gonna be the best fisher in Azeroth."},
{"LFG Blackrock Depths, full run.", "That place is a maze... are we ready for this?", "If we don’t get lost, it’ll be a miracle."},
{"I just hit level 80!", "Grats! Time to start grinding dungeons.", "Welcome to the big leagues!"},
{"Anyone got tips for PvP as a mage?", "Stay at max range and spam Frostbolt.", "And keep Ice Block ready for emergencies."},
{"Need help with this quest, these mobs hit hard!", "Where are you?", "Just outside Orgrimmar, near the troll village."},
{"Who’s the best WoW streamer?", "Asmongold, for sure!", "Nah, Preach has the best strats."},
{"Anyone ever rage-quit in a dungeon?", "I may have left halfway through Gnomeregan...", "That’s understandable. Those tunnels are brutal."},
{"Need more DPS for Naxxramas!", "What phase are you on?", "We’re stuck on Heigan... dance phase is rough."},
{"Has anyone seen the new mount?", "Which one, the golden dragon?", "Yeah! It’s so shiny, I need it!"},
{"Anyone here actually like archaeology?", "Only when it gives me cool toys.", "Yeah, but half the time it's just junk."},
{"Why is my DPS so low?", "Are you using the right talents?", "Maybe... or maybe I need better gear."},
{"Why did I just get kicked from the guild?", "Did you ninja-loot again?", "That was one time!"},
{"How’s leveling going?", "Slow, but steady. Got my first rare drop!", "Nice! What did you get?"},
{"Any hunters got an extra pet?", "We can't trade pets... yet.", "Aww man, I wanted a turtle like yours."},
{"Who's ready for Winter Veil?", "Already bought my reindeer mount!", "Just waiting to get my gift from Greatfather Winter."},
{"Looking for more for %instance%, need a %role% and two %class%s.", "I can join as a %class%!", "Perfect, just need one more DPS then we're set."},
{"Anyone know where to find the entrance to %instance%?", "Yeah, it’s just past %zone%. You can’t miss it.", "Thanks! I’ve been wandering around %zone% for ages."},
{"Anyone doing %instance%?", "We could use a %role%, if you're up for it.", "Sure thing, I’ll bring my %class%."},
{"LFM %bg%, need more %role%s!", "I can tank or DPS if needed.", "Awesome, let’s get this win!"},
{"Anyone else getting lag spikes in %zone%?", "Yeah, I thought it was just me.", "Hopefully, it clears up before the next %bg% starts."},
{"What’s the hardest boss in %instance%?", "I'd say the last boss... takes forever to down.", "Agreed, unless we get a really solid %role%."},
{"Anyone have experience with %class% tanking?", "I do! It’s all about keeping aggro and staying mobile.", "Mind if I ask you for some tips?"},
{"Could use help with a quest in %zone%—any takers?", "I can help, I’m in %zone% already.", "Thanks! Meet me by the quest marker."},
{"What’s the fastest way to farm gear in %instance%?", "Join a group that knows the fights and pulls quickly.", "And pray for RNG, of course."},
{"Anyone running %instance%?", "I need to finish my weekly for that place.", "Sweet, let's run it together."},
{"Anyone else think %bg% is just chaos?", "Yeah, but that’s what makes it fun!", "Until you’re the one getting camped at the graveyard..."},
{"Looking for a %role% for %instance%. We’re almost ready to pull!", "I can heal if needed.", "Perfect, let's go."},
{"Where's everyone hanging out tonight?", "I’m chilling in %zone%, fishing mostly.", "Might join you—%zone% is so peaceful."},
{"Anyone up for some PvP in %bg%?", "Count me in! I'll be on my %class%.", "Alright, meet you there!"},
{"I swear, %instance% hates me. I never get loot here.", "Same, I'm just here for the %class% gear.", "At least we’ll get some experience, if nothing else."},
{"Anyone else feel like %zone% is haunted?", "You’re not wrong—spooky stuff always happens there.", "I avoid %zone% whenever possible, honestly."},
{"Looking for %role%s and %class%s for %instance%!", "I'm a %class%, can I join?", "Sure! Now we just need a %role%."},
{"What's the best strategy for %bg%?", "Control the middle and capture flags quickly.", "Agreed, and avoid getting caught in the zerg."},
{"Could use help farming materials in %zone%. Anyone free?", "I’ll join! Could use some extra herbs myself.", "Alright, let’s meet up in %zone%."},
{"Anyone else farming mounts in %instance%?", "Yeah, but the drop rate is awful.", "Tell me about it. I've been running this every week."},
{"Anyone looking for a partner for quests in %zone%?", "I'm around there, need a hand?", "That would be great! I keep getting overwhelmed."},
{"What’s your favorite %instance%?", "I’d say %instance%—the boss fights are epic!", "Yeah, I love how challenging it is."},
{"LFM %bg%, need more DPS and a %role%.", "I’ll go DPS.", "Count me in as well."},
{"Where are the best farming spots in %zone%?", "Head to the northern part—mobs drop decent loot there.", "Great, thanks! I'll check it out."},
{"What's the best team comp for %instance%?", "Depends, but usually a solid %role% and strong DPS.", "True, but crowd control is key too."},
{"Can anyone show me the way to %instance%?", "It’s near %zone%, I'll guide you.", "Thanks, I keep getting lost."},
{"Need more for %instance%, any %class%s around?", "I can bring my %class%.", "Awesome! Now we just need a %role%."},
{"Who wants to run %instance% with me?", "I’ll come along, could use the practice.", "Alright, let’s queue up."},
{"Is %bg% always this chaotic?", "Yep, especially when people rush without a plan.", "Exactly—teamwork makes a huge difference."},
{"Anyone have spare mats for crafting?", "Depends, what are you looking for?", "Mostly herbs and ore."},
{"LF group for %instance%, I’m on my %class%.", "Cool, I’ll join on my %role%.", "Alright, let's gather up."},
{"Which class is best for %role% in %instance%?", "I’d say %class%, hands down.", "Agreed, their survivability is unmatched."},
{"What’s your favorite %zone% to hang out in?", "I love %zone%—great scenery and decent mobs.", "Same, it’s a nice place to relax."},

-- Adivces tips 
{"Anyone here use ConsolePort for controller play?", "Yeah, it’s great once you map everything, but takes a bit to get used to.", "I recommend using a PS5 controller—better sensitivity for targeting."},
{"Anyone know a good spot to farm for gold?", "I’ve been running Stratholme—decent drops and steady gold.", "Nice, also try %zone% for good gathering nodes."},
{"Where’s the best place to level a twink?", "For 19s, stick to %zone% for quick XP and decent gear.", "And for 29s, %zone% is great—tons of mobs and low competition."},
{"What’s the best FPS setting for low-end PCs?", "Turn off shadows, lower view distance, and use a custom resolution scale.", "Also, disable UI effects and particle density for better frames."},
{"Is anyone else hyped for the Arena Tournament this year?", "Totally! Rumor has it Savix and Ziqo might team up.", "That would be legendary—both are arena gods."},
{"Does anyone here know rare farming spots for %profession%?", "If you’re doing herbalism, %zone% is amazing for rare herbs.", "Miners should hit %zone%—lots of ore spawns there too."},
{"What’s the best spec for a level 39 twink %class%?", "Go with %class% for big burst. You’ll dominate PvP at that level.", "And make sure to get your BiS gear from Scarlet Monastery!"},
{"I need crafting recipes for Alchemy. Where’s the best place to look?", "Check WoWHead for each recipe’s drop location, but %zone% has some good ones.", "Don’t forget to check vendor recipes—some of them are super rare."},
{"Anyone here good at setting up WeakAuras?", "I can help! Start with the basics and layer them for PvE and PvP.", "For a clean setup, follow the Venruki guide—he covers everything in detail."},
{"Looking for noob-friendly addons?", "Titan Panel is good for tracking XP and gold.", "Immersion is a must for questing, adds a nice cinematic feel to dialogs."},
{"How’s mythic dungeon been going for everyone?", "Pretty tough this season, mechanics are unforgiving.", "Yeah, %instance% especially—watch out for the add phases."},
{"What’s a good spec for twinks around level 29?", "For %class%, %spec% is great for PvP burst damage.", "And get your BiS from %instance% for the best gear advantage."},
{"Any good farming spots for rare elites?", "Try %zone%, there are a few rare elites that drop good loot.", "Agreed, plus they give solid XP if you’re leveling."},
{"What’s a good addon for immersion?", "DynamicCam is amazing—makes the game feel like a new world.", "Combine it with Immersion, and it feels like an RPG."},
{"Does anyone know how to boost FPS in %instance%?", "Turn off nameplates, lower particle density, and try DX11 mode.", "Great advice—also avoid add-ons that use a lot of memory."},
{"Any news on the WoW Arena Tournament this year?", "Yeah, it’s kicking off in March. Huge prize pool too!", "Can’t wait! Rumor has it Payo might be competing."},
{"Anyone know a good UI setup for PvP?", "Keep it simple. Use Gladius for arenas and NameplateCooldowns.", "And WeakAuras for tracking key abilities in PvP."},
{"I’m looking for twink gear for my level 49 %class%. Any tips?", "Blackrock Depths has good armor pieces. Also check %zone%.", "And keep an eye on the AH for rare BoE gear."},
{"What’s the best addon for auction tracking?", "Auctioneer is great—tons of tools for buying and selling.", "Yeah, also use TradeSkillMaster for serious gold-making."},
{"Does anyone here role-play?", "Sometimes! I love setting up lore-friendly outfits for my character.", "Check out the TotalRP3 addon if you’re into that—it’s perfect for RP."},
{"What's the best way to level enchanting?", "Make green items and disenchant, or buy mats off the AH.", "Don’t forget about WotLK green items—they give solid dust and essences."},
{"Anyone know where to find rare recipes?", "Some rare recipes are in Dire Maul. And check %zone% vendors.", "Thanks! Didn’t realize some vendors have exclusive recipes."},
{"Best way to get gold as a %class%?", "Skinning in %zone%—lots of beasts and high demand for leather.", "You can also farm dungeon mobs for vendorable greys."},
{"Any advice for leveling in %zone%?", "Bring a lot of potions; mobs are tough here.", "And watch out for patrols—they can ruin your day in hardcore."},
{"Best resources for macros?", "Check the GitHub repo for ConsolePort macros if you play with a controller.", "Also, /macro in-game to practice chaining your abilities."},
{"Anyone else following the WoW 2024 arena news?", "Yeah, super competitive this year. Ziqo and Xaryu are dominating!", "Makes me want to get back into arena myself."},
{"I need help on crafting rare blacksmithing items.", "Some rare drops are in %instance%, and you can farm %zone% elites.", "Blacksmithing is tough, but the BoP items are worth it."},
{"Anyone have UI recommendations?", "ElvUI is solid, very customizable.", "TukUI is also good—great for a minimalist look."},
{"Looking for addons that add immersion?", "DynamicCam, Immersion, and Musician. They make the world feel alive.", "Add some RP sound effects for maximum effect."},
{"Anyone know the best spot to farm leather?", "Try %zone%, tons of skinnable mobs there.", "And use a macro to auto-loot faster!"},
{"What’s the best spec for level 19 twinks?", "For %class%, go with %spec%—insane burst for that bracket.", "Agreed, and pick up the %instance% gear for BiS."},
{"Anyone farming mounts?", "I’m farming %instance% for the rare drop mount there.", "RNG is brutal, but it’s worth it for the flex."},
{"Where’s the best place to get rare pets?", "Try %zone%—several rare spawns drop unique pets.", "Good spot, but watch out for competition."},
{"Best settings for WoW on a low-end PC?", "Disable shadows, drop resolution, and set view distance to low.", "Try to close any unnecessary add-ons, too."},
{"Does anyone use ConsolePort with WoW?", "Yep, it works well with a PS5 controller and feels super immersive.", "You can even macro some abilities for quick access."},
{"What's the best addon for beginners?", "Questie is a must-have for quest tracking.", "Also, use Details for damage meters—it’s simple and clear."},
{"What’s a good spec for mythic dungeons?", "%class% is great for consistent damage output and utility.", "True, plus it’s easy to find groups as %class%."},
{"Where can I find the best PvE addons?", "Check curseforge.net for updated lists; Deadly Boss Mods is essential.", "Also, WeakAuras for tracking mechanics."},
{"Any secret routes for gold farming?", "I farm %zone%—solid drop rate on greens and mats.", "Try %zone% as well; great spot for gathering professions."},
{"What's the best PvP setup for %class%?", "Run %spec% for solid burst damage in arenas.", "And spec into crowd control if you’re running twos."},

-- Single-line Phrases
{"LF more for UBRS, need tank and healer!"},
{"Who else misses the old battlegrounds?"},
{"Anyone know if they nerfed mages again?"},
{"WTS rare pet - meet me by the Ironforge bank."},
{"Finally got my epic flying mount!"},
{"Any ideas for a new transmog look?"},
{"LF gem-cutter for blue quality gems."},
{"I’ve been farming for this trinket forever!"},
{"Why is there a gnome in the auction house yelling about muffins?"},
{"Why are there so many skeletons outside the raid?"},
{"I just got kicked for rolling need on a grey item..."},
{"Any other rogues here miss Pick Pocketing?"},
{"Got my first legendary! Can't believe it!"},
{"LF people for Alterac Valley premade."},
{"Took me 100 tries, but I finally got the mount!"},
{"Anyone else farming herbs? Prices are through the roof!"},
{"Can someone share a warlock summon? My hearth is on cooldown."},
{"Let's all go fishing in Booty Bay!", "guild"},
{"Anyone remember the old AV battles that lasted all day?"},


----------------------Start adding chat text here-------------------------
"Selling Silver Scales Breastplate, 5G each.",
{"Selling epic weapon, slightly used. Only dropped once...per boss fight.", "How many bosses has it survived?", "Let's just say it's seen more floors than a janitor.", "That weapon's got more history than the Scarlet Monastery.", "Epic weapon or archaeology artifact?"},
{"WTB someone to carry me through a dungeon. Offering friendship and my eternal gratitude.", "Is that gratitude epic quality?", "Only if you don't let me die.", "Gratitude and a side of repair bills, coming up!", "Best deal in Azeroth!"},
{"WTS invisibility potions. Perfect for ninja looting!", "Do they work on guildmates?", "Only if they don't have anti-ninja goggles.", "Ninja loot now, apologize later.", "Invisibility: the gift that keeps on giving."},
{"Auctioning off a date with my main character. Comes with a free mount ride!", "Is the mount epic at least?", "Of course, and it's got two seats!", "Hope the mount's more reliable than my last date...", "Romance, WoW style."},
{"WTS rare pet. Slightly disobedient but has character.", "Does it do tricks?", "Only when it's not busy ignoring my commands.", "Does it come with a manual?", "Rare pet with an attitude, a bargain!"},
{"Looking to trade my soul for epic gear. Any takers?", "Is the soul epic quality?", "Depends, does frequent dying lower its value?", "Gear first, soul later. No refunds!", "Best trade of my afterlife!"},
{"WTS stack of [Mystery Meat]. Not responsible for any side effects.", "What kind of side effects are we talking?", "Uncontrollable dancing, mostly.", "Perfect for my next raid!", "Dine and dance with [Mystery Meat]!"},
{"WTB luck potion. My drop rates are cursed.", "Can't sell you luck, but I have a four-leaf clover.", "Does it work in raids?", "Only if you rub it and chant the loot prayer.", "Loot luck, now in potion form!"},
{"Selling a slightly haunted helmet. Previous owner's spirit included.", "Does it give extra wisdom?", "Only if you consider moaning at midnight wise.", "I'll take it for the ghost stories alone!", "Haunted helmet, the real spooky deal!"},
{"WTB a map to find my way out of Wailing Caverns.", "You mean you're still stuck in there?", "Since last Tuesday... Send help.", "I'll trade you for a breadcrumb trail.", "Wailing Caverns: the maze you never escape."},
{"WTS [Mysterious Potion]. Effects may vary. No refunds.", "May vary? Like how?", "Last guy turned into a sheep for an hour.", "That's some baa-d luck.", "Sheep today, who knows tomorrow!"},
{"Looking for a mage to conjure me a sandwich. Starving here!", "What kind of sandwich are we talking?", "Anything that doesn't taste like mana.", "One conjured ham on rye, coming up!", "Magic meals, just a spell away."},
{"WTS invisible cloak. Disclaimer: Might not actually be invisible.", "How do we know it's not just an empty hanger?", "You just have to believe!", "I bought one, now I can't find it...", "The best cloak you'll never see!"},
{"WTB the patience to deal with pugs.", "Isn't that sold out everywhere?", "I'd settle for a pug that knows north from south.", "How about a compass instead?", "Pugs: where every direction is pull!"},
{"WTS [Bag of Laughs]. Contents: dad jokes and puns.", "How effective are they?", "Let's just say you'll groan more than laugh.", "Perfect for my next guild meeting!", "Laughter is the best loot."},
{"WTS Time-Lost Artifacts. Disclaimer: May actually just be junk.", "Define 'artifact'.", "It's very ancient... looking.", "So, like, last expansion ancient?", "Time-Lost or simply forgotten!"},
"Buying Air for 400G a set, buying [Frozen Orb] for 100 each.",
{"Anyone know a good spot for farming [Heavy Leather]? Need a bunch for crafting.", "Try the raptors in Wetlands. Decent drop rate there.", "Thanks for the tip! Need anything in return?", "No worries, just pay it forward to the next crafter in need."},
{"Looking for advice on the best tanking gear for early raids.", "You should focus on increasing your stamina and armor stats.", "Got it. Any specific dungeons I should run?", "Try running Blackrock Depths. It has some solid gear drops for tanks."},
{"Struggling with the final boss in Maraudon. Any tips?", "What class are you playing?", "Resto druid.", "Keep your HoTs up and watch out for area damage. Kiting helps too.", "Great, I'll give that a try. Thanks!"},
{"Does anyone have experience with the auction house? Not sure how to price my items.", "It depends on the item. Check what others are selling it for as a start.", "Should I go higher or lower than the average?", "Match the average. Going too low undervalues your item, too high and it won't sell."},
{"LF someone experienced with herbalism to help identify a few plants.", "I can help you out. What did you find?", "Not sure, found them in Ashenvale. They're sort of purple and spiky.", "Sounds like Gromsblood. It's quite valuable, good find!"},
{"Any guilds out there good for new players? Just started a week ago.", "Welcome to the game! What's your class and level?", "Level 15 warrior. Still figuring things out.", "Our guild is newbie-friendly. We do regular dungeon runs and help with quests."},
{"Can anyone recommend a good leveling route for Eastern Kingdoms?", "Start with Redridge Mountains, then Duskwood. Great quests there.", "Should I avoid PvP areas?", "If you're not into PvP, yeah. Stick to safer zones like Loch Modan."},
{"Looking for a group to do some casual battlegrounds. Not super competitive, just for fun.", "Count me in! I'm tired of the serious PvP grind.", "Great! Let's just enjoy the game and have some laughs.", "Sounds good. Let's keep it light and fun."},
"%role% looking for weekend raid team",
"Anyone for leveling in %zone%?",
"How many people needed to raid SW?",
"Looking for a questing partner in %zone%.",
"<Sentinel> is now recruiting. We require a 4500+ GS and max professions. Raid times are Tuesday, Wednesday evening 8 to 11:30. We are mostly looking to fill 10-man team positions.",
"Buying Titan Ore, whisper.",
"LFM for %zone% questing.",
"LF party in %zone%.",
"I hate questing in %zone%. Where can i go instead for my level?",
"25 NAXX5 group, quick run. explosive DPS needed...",
"LFM for UBRS Jed/Rend runs. First Briarwood Reed res.",
"[Simple Cape] for sale at a very low price",
"LFM 25-man Ulduar FL run. Need some high gearscores",
"%role% looking for a pvp friend",
"LF arena partner for 2s. 1880+ only please.",
"LF 3s carry.",
"Can 10 people manage SW?",
"LFM for BWL. no laggy connections, need all classes. Bads will be booted.",
"10-man Black Dragon, any SM, NQ, SS?",
"<Eight Memories> is a new guild recruiting. We run DKP and are open to all players, no gear requirements. Active raid times TBD.",
"LFM BRD Lava run. Need %role%.",
"%instance% looking for T, %role%, DPS",
"SW transmog contest forming! Come and get all the prizes!",
"Buying a [Combustion Bracers], selling offers",
"25 NAXX5 group, fast recruitment, explosive DPS needed",
"Buying [Infinite Dust] [Infinite Dust]",
"10 ULD, looking for 4100+ melee and NQ, MS",
"Selling G, selling G, pm for details",
"10-man Ulduar, looking for DPS and %role%",
"[Glory of the Ulduar Raider (10-man)] half-achievement team. 4 guardians starting. Looking for NQ, dual SMSS with GSMMMMM",
"25 NAXX,...........5 group, looking for DPS, melee and ranged who need trinkets, hurry up",
"10-man ULD new CD!! Looking for strong NQ!! MS!!! And ZS!!! Strong crushing team!! Bring GS 7=3 at least till UG",
"%instance% looking for strong T and DPS, last wave, hurry up",
"Anyone for 25-man RS?",
"Buying Eternal Fire 20! Air 15! Earth 6! Shadow 5! Water 4! Life 30! Saronite Ore 15! Saronite Bar 30! Borean Leather 20/set Thick Borean Leather 130/set Icy Dragonscale 1G Nerubian Chitin 1G Icy Fang 2G Frozen Orb 100 Rune Orb 210! COD accepted.",
"[Frostweave Cloth] [Borean Leather] 25 sets each, contact if needed",
"Hero League 2 team preparing for TOC recruiting. Inviting friends to experience game fun. DM if interested.",
"[Frozen Orb]=110G, [Azure Thread]=32G!!",
"BWL transmog team, contact if interested, already 2 people, no AL",
"Daily R-point size game, 200G a round, contact if interested",
"Lao Pao Er guild, gathering two 10-man ULD full-clear teams. Preparing for TOC, recruiting DZ, AM, NQ, Evil DK, main force upon joining. Requires some equipment foundation, new team members double points for bosses. Give me a stable you and I give you a quality",
"YXSL, new progress, daily raid, looking for 4000+ %role%s, magic DPS, LR, contact if interested",
"YXSL, looking for 4000+ %role%s, magic DPS, LR, contact if interested",
"Buying King's Shadow Amber Scarlet Stone Fear Purple Yellow Crystal 120G Frostweave 4G Icethorn Snake Venom 32g Witchflower 151G/set Damaged Necklace 88g support COD",
"<Golden Times> recruiting elite players of all classes~ All-heart DKP new CD welcomes all class masters to join, let us feel the friendship and joy that WoW once brought us, activity time 456 every night 8-11~ waiting for you to join!",
"1:150G selling 100 Crystal Coins. If needed, contact me.",
"Selling/crafting Ulduar 226 ilvl cloth leather mail plate crafting belts and shoes, buying Frozen Orb 100g Rune Orb 220g King's Amber Scarlet Red Fear Stone Purple Yellow Crystal 121g Titansteel Ore 125g Saronite Ore 15g, Earth 7.1 Fire 26.5 Air 16 Shadow 5 Water",
"Buying Eternal Earth 7G Eternal Life 32G/group Fire 26 Air 16 Shadow 5 Water 7 Saronite 15.5 Titan 126 Frozen Orb 101 Borean Leather 22G Spider Silk Ice Bug Leather 1.5 support COD instant purchase",
"Buying 150 Witchflower, support mail",
"HSL looking for T and DPS",
"Selling account 80DK dual-gathering max dual-spec cheap sale interested MMM same account 3 classes FS4200 DK3200 SM4500 no time interested MMMAG gate see account",
"10-man EoE looking for experienced players",
"LFM Ulduar, looking for various experienced drivers",
"LFM AQ runs, looking for %role%",
"10-man UBRS, looking for %class% and %role%",
"New guild <Harem> preparing for TOC recruiting stable members. Level 80 stable players okay. Weekly 12 evenings 7.30-11 for 25-man activities. Interested private chat. Other times guild organizes 10-man for improvement!",
"HSL looking for tough T, can start 4=1",
"Selling [Infinite Dust]70 [Frostweave Cloth Roll]25",
"Scammer online, everyone come and watch...",
"Need love not WoW, looking for true love~~...",
"Shaman looking for Naxx... almost 80...",
"%zone% quest anyone?...",
"Zul'Drak Arena quest, need a %role%...",
"Starting Stockades, anyone wanna come?",
"LFG %instance%, need %role%. Let's snag some sweet loot!",
"Any groups running%instance%? I'm a DPS ready to roll.",
"%role% LFG for any dungeon. Have heals, will travel.",
"Looking for more for Strath UD. Come for the run, stay for the Baron's mount!",
"LFM Molten Core, need 2 %role%s. On Domo, let's get this fire party started!",
"Mage LFG %instance%. I bring portals and food, you bring the fun.",
"Hunter looking for group for %instance%. I promise my pet won't pull extra mobs... much.",
"LF1M UBRS, need rogue for those sweet lockpicking skills.",
"LFG Maraudon, Princess run. Let's turn her into compost.",
"Need a few more for Onyxia. Let's make some dragon stew.",
"Shadow priest LFG for any raid or dungeon. I'm like a Swiss Army knife, but with more shadow.",
"LF2M for %instance%, need DPS and %role%. Tryhards beware!",
"Warrior tank LFG, ready to face any challenge. Yes, even that one.",
"LFM for a chill %Instance% run. No rush, just fun and loot.",
"Rogue LFG. I've got lockpicks, poisons, and bad jokes.",
"LF1M %role% for quick UBRS. Keyholder here, let's unlock some chaos!",
"Paladin %role% LFG. Will turn undead and keep you alive, usually in that order.",
"LF3M for Lower Blackrock Spire. Need %role%. Let's get 'er done!",
"Resto druid looking for group. I can heal, tank, DPS, and make a mean salad.",
"LFM Naxxramas. It's like a party, but with more undead and frost damage.",
"Join <Cereal Killers>! We slay monsters before breakfast. Seeking night owls and early birds for dawn patrols in Azeroth!",
"<Darnassus Dance Party> is recruiting! If you can /dance and fight simultaneously, we want you! BYO disco ball.",
"Looking for a guild that appreciates fine wine and finer loot? 'Merlot Marauders' is now recruiting connoisseurs of chaos!",
"'Loot Hoarders Anonymous' needs you! We can't promise to cure your loot addiction, but we'll definitely enable it.",
"Join 'The AFKers'! Perfect for those who love to play, but have a life... sort of. Now accepting applications from fellow Alt-Tab experts.",
"'The Lag Vanquishers' are recruiting! If you've ever been killed by a lag spike, you're one of us. Revenge is best served in low latency.",
"Become a 'Goblin's Worst Nightmare' today! We spend gold faster than we make it. Currently seeking treasure hunters and auction house barons!",
"'The Thunder Bluff Kite Club' is looking for members! If you enjoy long falls and sudden stops, join us for our next 'flight'!",
"<Hogger's Heroes> wants you! Join us and be part of the legend. Requirements: Fearlessness and a love for respawn runs.",
"Calling all night owls! 'Midnight Raiders' is recruiting. Because the best loot drops after midnight... right?",
"'The Wandering Turtles' are slowly expanding! Join us if you believe slow and steady wins the race (to the loot).",
"'The Bank Alt Fashionistas' are here! Looking for members with a passion for inventory management and top-notch tabard style.",
"Be part of 'The Epic Failures'! We might not always succeed, but we fail in style. Now recruiting optimistic pessimists!",
"Join 'The Undergeared Underdogs'! We believe in challenging content – like trying to solo a raid boss. Gear optional, courage required!",
"'Grumpy Old Gnomes' is recruiting! Must be short, cranky, and have a passion for explosive engineering mishaps.",
"Are you 'Not Prepared'? Neither are we! Join us and Illidan won't be the only one disappointed. Now recruiting casual chaos creators!",
"WTB Teleport to Dal, 5g.",
"LF Teleport to Shattrath, 1g.",
"WTS |cffa335ee[Deathcharger's Reins]|r |cFFFFC0C0for a good price. Get your ride in style! Whisper me for details.|r",
"WTB |cff1eff00[Large Brilliant Shard]|r. |cFFFFC0C0Paying well, need for enchanting. PST with offers.|r",
"WTS |cffffffff[Runecloth]|r |cFFFFC0C0in bulk. Good for rep grind or first aid. Hit me up for a sweet deal!|r",
"LF Blacksmith to craft |cff0070dd[Arcanite Reaper]|r. |cFFFFC0C0I've got the mats and a tip ready. PST.|r",
"WTS |cffa335ee[Krol Blade]|r. |cFFFFC0C0Rogue's dream weapon. Whisper for price.|r",
"WTB |cff0070dd[Shadowcraft Bracers]|r. |cFFFFC0C0Completing my set. PST with price.|r",
"WTS stacks of |cffffffff[Thorium Bars]|r. |cFFFFC0C0Great for leveling engineering or blacksmithing.|r",
"Looking for a tailor to make |cffa335ee[Truefaith Vestments]|r. |cFFFFC0C0I have all the mats. Will tip generously!|r",
"WTS Epic Hunter BOE set. Get geared quick! PM for details and prices.",
"WTB |cff1eff00[Greater Eternal Essence]|r |cFFFFC0C0for enchanting. Need several, paying top gold.|r",
"WTS |cffa335ee[Spellpower Elixir]|r|cFFFFC0C0x20. Boost your DPS for tonight's raid. Bulk discount available!|r",
"LF Enchanter to do |cff0070dd[Crusader]|r |cFFFFC0C0enchant. I have the orbs and will tip. PST.|r",
"WTS |cffffffff[Major Healing Potions]|r. |cFFFFC0C0Be raid ready! Bulk deals available.|r",
"WTB |cffa335ee[Hand of Edward the Odd]|r. |cFFFFC0C0Name your price. Serious buyer here.|r",
"WTS |cffa335ee[Choker of the Fire Lord]|r |cFFFFC0C0from MC. BIS for many classes. PST offer.|r",
"WTB all your |cffffffff[Copper Ore]|r! |cFFFFC0C0Paying more than AH prices. Whisper me for quick gold.|r",
"WTS |cff0070dd[Robe of the Archmage]|r. |cFFFFC0C0Perfect for mages. Crafted and ready to wear!|r",
"LF someone to craft |cff0070dd[Titanium Spellshock Necklace]|r. |cFFFFC0C0Got mats + tip. PST if you can help!|r",
"LF tailor for |cff1eff00[Green Linen Shirt]|r. |cFFFFC0C0Got mats + tip. PST if you can help!|r",
"WTS |cffa335ee[Arcanite Bars]|r. |cFFFFC0C0Stock up for your legendary or other crafts. Whisper for price.|r",
"WTB |cff0070dd[Frozen Rune]|r |cFFFFC0C0for crafting. Paying well, need multiple. PST if you have any to spare.|r",
"When Chuck Norris enters a room, he doesn't turn the lights on. He turns the dark off.",
"Chuck Norris can divide by zero.",
"Chuck Norris doesn't sleep; he waits.",
"Chuck Norris can slam a revolving door.",
"Chuck Norris can unscramble an egg.",
"Chuck Norris's tears cure diseases. Too bad he has never cried.",
"Chuck Norris once counted to infinity. Twice.",
"Chuck Norris doesn't need mounts in Azeroth. He just walks faster than any epic mount.",
"Chuck Norris's Hearthstone has no cooldown. He's always home.",
"Chuck Norris's fishing skill is so high that even Murlocs ask him for tips.",
"Chuck Norris doesn't need a raid group. He is the raid group.",
"Chuck Norris's DPS is so high, bosses beg for mercy.",
"Chuck Norris can transmog gear from one expansion to another.",
"T-man's Night Elf Mohawk is the real reason for the Cataclysm.",
"T-man's Night Elf Mohawk once tamed a dragon with a single flex.",
"They once tried to implement Chuck Norris as a raid boss in WoW. However, during testing, nobody could survive the 'Roundhouse Kick' phase.",
"LF tailor to make |cff0070dd[Royal Moonshroud Robe]|r |cFFFFC0C0 . I have all the materials and will tip generously. PST for a quick deal!|r",
"LFG for Heroic Dungeons, need 1 healer and 1 DPS. Gear score 4500+ required. Whisper me for invite!",
"WTT |cff0070dd[Crusader Orb]|r |cFFFFC0C0  for|r |cff0070dd[Runed Orb]|r |cFFFFC0C0, 1:2 trade. Whisper me if interested!|r",
"Buying |cffFFFFFF[Heavy Borean Leather]|r |cFFFFC0C0  in bulk. Paying well above AH prices. PST with your offer!|r",
"LF Blacksmith to craft |cff0070dd[Tempered Titansteel Helm]|r |cFFFFC0C0 I have mats and will give a good tip. Whisper me!|r",
"Auctioning a rare pet |cff0070dd[Proto-Drake Whelp]|r |cFFFFC0C0 Starting bid at 5000g. PST to place your bid or buyout for 10k!|r",
"Selling cheap enchants! |cff0070dd[Superior Spellpower]|r |cFFFFC0C0,|r |cff0070dd[Greater Assault]|r |cFFFFC0C0 , and more. PST for prices and availability.|r",
"LF2M for Naxxramas 25, need 1 %role% and 1 %class%. Experience and proper gear required. Whisper for invite.",
"WTS |cff0070dd[Frozen Orb]|r |cFFFFC0C0x10, bulk discount available. Whisper me for a great deal!|r",
{"WTS enchanted boots, never run out of style.", "Do they also never run out of durability?", "Only if you avoid lava and dragons.", "Stylish and dragon-proof, a rare combo!", "Fashion meets function in Azeroth!"},
{"WTB a guide for the Auction House. I keep buying high and selling low.", "Is it a strategy or a curse?", "Let's call it a 'learning experience.'", "I can teach you, but I charge in gold!", "Auction House 101: Buy low, sell... oops."},
{"WTS legendary fishing pole. Only used once, scared off the fish.", "Do the fish tell tales about it?", "Yes, it's the one that got away!", "Catch of the day: epic fishing tales!", "Legendary pole, for legendary fish stories."},
{"WTB a pet that doesn't judge me for my poor battleground skills.", "Do pets even judge?", "Only with their little pet eyes.", "I have a non-judgmental turtle available.", "Find a friend who's slow to judge!"},
{"WTS rare cooking recipe. Results may vary.", "Does it require exotic ingredients?", "Only if you consider 'edible' exotic.", "MasterChef Azeroth edition.", "Cook at your own risk – or delight!"},
{"Looking to swap heroic tales. Mine involve mostly running away.", "Running away bravely, I hope?", "Bravely and with great speed!", "I'll trade you a tale of accidental heroism.", "Heroes or zeros, stories galore!"},
{"WTS [Bag of Holding]. May or may not hold your hopes and dreams.", "Capacity for existential crises?", "And a side pocket for regrets.", "Every adventurer's essential.", "Hold more than just items, hold possibilities!"},
{"WTB an alarm clock that works for early raid mornings.", "Do you sleep through boss fights too?", "Only the unimportant ones.", "I'll trade you for a rooster. Natural alarm!", "Wake up to Azeroth's calls of duty!"},
{"Selling maps to secret fishing spots. Fish tales included.", "Any legendary locations?", "Where the fish are as big as boats!", "Throw in a tall tale, and you've got a deal!", "Secret spots for epic catches!"},
{"WTB a joke book to entertain my guild. They're a tough crowd.", "How tough are we talking?", "Tougher than a level 1 boar.", "I have a book, but it’s all chicken jokes.", "Keep your guild clucking with laughter!"},
"LFG for any raid where my talent for accidentally pulling extra mobs is considered a skill.",
"Looking for %instance% group that doesn't mind if I confuse my healing spells with emotes.",
"LFM for %instance% run. Requirements: a sense of humor and a high tolerance for chaos.",
"LFG where my strategy of 'panic and randomly hit buttons' is an acceptable raid technique.",
"Looking for a group that appreciates interpretive dance as a form of battle strategy.",
"LFM for %instance%. Must be okay with me narrating the adventure like a fantasy audiobook.",
"LFG for an epic quest. Must bring your own snacks and a love for dramatic, unnecessary detours.",
"LF %instance% group where my pet's habit of aggroing extra mobs is seen as a fun surprise, not a problem.",
"Looking for a raid group where 'I thought it was a shortcut' is a valid excuse.",
"LFM for chill %instance% run. Bonus points if you can tell jokes while dodging boss mechanics.",
{"Yo mama so fat, she exalted with McDonalds.", "Did she get the McMount reward?"},
"WoD was the best expansion ever.",
"Your momma's so fat chain heal hits her twice",
"Yo mama is so fat her 4pc set bonus was fries and a coke!",
"Your momma so fat she sat on the [Black Temple] and turned it into [Sunken Temple]!",
"Anyone up for a quick and easy %instance% run?",
"Anyone need help with any group quests?",
"|cff0070dd[Thunderfist's Mighty Hammer]|r |cFFFFC0C0WTS, best offer! It smashes! It crashes! It turns your enemies into ashes!|r",
"WTB |cffFFFFFF[Elixir of Giant Growth]|r |cFFFFC0C0Trying to look taller than my gnome girlfriend...|r",
"LF tailor to craft |cff0070dd[Robe of Eternal Night]|r|cFFFFC0C0. I provide mats. Will tip!|r",
"The end is nigh! Sell me your gear cheap and enjoy your final days!",
"WTB [Broken I.W.I.N. Button]. I heard it's a sure way to win PvP!",
"Anyone seen a rogue around here? He stole my heart... and my |cffFFFFFF[Bag of Shinies]|r",
"WTS lore explanations. Ever wondered why Thrall left? Or who shot first, Sylvanas or Greymane?",
"LF someone to just... talk to. About anything. WTB a friend?",
"WTS |cffFFFFFF[Gnomish Army Knife]|r |cFFFFC0C0It slices, dices, and makes julienne fries!|r",
"WTB directions to Orgrimmar. Keep getting lost... This map is useless!",
"LF chill people for a laid-back %instance% run. No rush, just fun!",
"think I finally found the perfect spot for meditation. So peaceful.",
"Anyone else love exploring old zones just for the nostalgia?",
{"Just found out my guildmate stole my loot. Traitor!", "This is why I don't join guilds. Too much backstabbing."},
"Sometimes, I just log in to listen to the game’s soundtrack. So relaxing.",
"Did you all hear about the guild leader from Vanquished who vanished with all the guild's funds?",
"I just like to watch the world burn. Anyone want to join me for some chaos?",
"I just logged in... what did I miss?",
"Do you enjoy snacks as much as you enjoy raids? Is your favorite boss fight against the Pizza Elemental in the Dining Room Dungeon? Well, do we have a guild for you! Join <Fat Kids Lag IRL>!  Whether you're as light as a feather or have gravitational pull, all are welcome!",
{"Why is it that every time I log in, there's a new villain in town? Can't we have peace for once?", "Because peace is boring! We need action, battles, and drama!"},
{"Did somebody say, |cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r|cFFFFC0C0?|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r", "|cFFFF8000[Thunderfury, Blessed Blade of the Windseeker]|r"},
"LF someone to critique my |cff0070dd[Epic Poem of Guild Drama]|r. |cFFFFC0C0Will pay in emotional support!|r",
"Will trade rare cooking recipes for epic tales of your adventures!",
"Anyone up for a game of hide and seek in Dalaran? Winner gets a |cffFFFFFF[Bag of Mystery Trinkets]|r|cFFFFC0C0!|r",
"WTS advice on how to talk to quest NPCs. They're just misunderstood, really.",
"Anyone know how to get |cffFFFFFF[Sticky Glue]|r |cFFFFC0C0off my hands? Asking for a friend.|r",
"WTB [Map to Hidden Treasure]. I promise I won't spend it all in one place!",
"Anyone else's pet acting weird today? Mine just tried to sell me insurance.",
"LF group to explore [The Great Unknown]. Must bring own snacks and sense of humor!",
"Anyone seen a lost sheep around? Answers to the name Fluffy. Reward if found!",
"WTB [Mystery Potion]. The last one turned me green for a week. Want to see what's next!",
"LF fashion advice. Can't decide between |cff0070dd[Robe of the Cool]|r |cFFFFC0C0and|r |cff0070dd[Stylish Tunic]|r",
"Anyone want to swap ghost stories? I've got a chilling tale about the Haunted Gold Mine.",
"WTB [Ancient Artifact]. Doesn't matter what it does. I just like collecting old stuff.",
"LF someone to practice dueling with. Disclaimer: I'm terrible, but enthusiastic!",
"WTS |cffFFFFFF[Bag of Laughs]|r|cFFFFC0C0. Guaranteed to brighten your day or your money back!|r",
"Anyone up for a scavenger hunt in Stormwind? First clue is 'Where the King's Shadow Lies'.",
"LF group to test my new invention: |cffFFFFFF[Portable Campfire]|r|cFFFFC0C0. Great for spontaneous marshmallow roasts!|r",
"WTB [Elixir of Eternal Friendship]. Or just a regular friend. Either works.",
"Can someone teach me how to knit? Want to make |cffFFFFFF[Cozy Socks]|r |cFFFFC0C0for winter.|r",
"LF advice on pet training. My voidwalker keeps eating my homework.",
"Anyone want to join my book club? This week's read: 'The Lich King's Diary'. Spoiler: He's misunderstood.",
"WTB [Map to Secret Fishing Spot]. I swear I won't tell a soul!",
"LF fellow explorers for a trip to [Uncharted Island]. Must be okay with potential pirate encounters.",
"Is it just me, or does the |cffFFFFFF[Mysterious Floating Orb]|r |cFFFFC0C0look like it's judging us?|r",
"Anyone want to start a parade through the city? I've got a |cffFFFFFF[Box of Costumes]|r",
"WTB [Book of Calm Thoughts]. Trade chat is making my head spin today.",
"LF group to take silly screenshots with. Must enjoy costume changes and dramatic poses!",
"Anyone else collect weird stuff? I've got a whole tab of just left shoes...",
"WTB [Secret to Eternal Happiness]. Or just a slice of pie. Pie works too.",
"My wife would be a good cooking trainer.",
"Are you skilled, fearless, and ready to take on the world? Great, we need someone to carry us. <Cookie Crawlers> is recruiting!",
"Ever wanted to be part of a group that's one wipe away from becoming a support group? <Wipe Masters Anonymous> is recruiting! Therapy sessions included.",
"WTB all your |cffffffff[Peacebloom]|r |cFFFFC0C0at market price! Bulk sellers welcome. Let's make a deal!|r",
"DPS looking for a group to run %instance%. Experienced and geared. PST pls!",
"LF Tailor to make me |cffffffff[Simple White Robes]|r|cFFFFC0C0. Will provide mats and tip generously. Please whisper!|r",
"Auction House Alert: Massive sale on |cffffffff[Thorium Ore]|r|cFFFFC0C0! Stock up now before prices go back up!|r",
"When Chuck Norris plays WoW, the servers never go down. They're too afraid to interrupt his gameplay.",
"How does a tauren hide in a cherry tree? He paints his hooves red. Ever seen a tauren in a cherry tree? Works, doesn't it?",
"How many World of Warcraft players does it take to change a light bulb? Ten. One to change the bulb and nine to complain about how it was better before the change.",
"How to make a small fortune in WoW: Start with a large fortune, then buy out all materials on the Auction House.",
"LFM for %instance%, need all roles. PST! Must bring your own potions, snacks, and dad jokes.",
"Anyone else notice that goblins treat the Auction House like their personal comedy club?",
"If you name your character ChuckNorris the Lich King teleports to the starting zone and just gives you Frostmourne.",
{"6 - 6 * 6 = ?", "0", "0", "0", "-30"},
"Why do they call it invincible when you can see it?",
{"Does anyone know where to get some good sl*t mogs?", "Have you checked your mom's closet?"},
"Yo momma so fat she got stuck on level 60 as she couldn't fit through the Dark Portal.",
{"Why do they call it an Xbox 360?", "Because when you see it, you turn 360 degrees and walk away."},
"Guys? How do I mine fish?",
"LF Healer for STD.",
{"Anyone for Throne of Thunder?", "Wrong expansion...", "I call my toilet the Throne of Thunder too!"},
"Have you guys seen the little campfire and tent they added when you type /camp ?",
"Blizzard asked Chuck Norris what, if anything, he could remember about Vanilla.  Thus Classic was born.",
"When Chuck Norris plays WoW, the NPCs complete quests for him.",
"Yo mama so fat Earth Shield expired before it made a single orbit",
"Yo momma so fat when a rogue shadowstepped her, he got a loading screen.",
"How many rogues does it take to kill a Pally? Two. One to ambush and one to wait at the innkeeper.",
"Did you guys hear about the time Chuck Norris entered a dungeon solo? He won a 5-man achievement.",
"Lol! Chuck Norris doesn’t need a mount. He makes the world move beneath him.",
"That’s nothing. Chuck Norris casts Pyroblast by snapping his fingers. No mana cost.",
"Chuck Norris was once bitten by a venomous snake. After three days of pain and agony... the snake died.",
"Ever wonder why there are no Chuck Norris class in WoW? Because the first ability, 'Roundhouse Kick', instantly defeats the final boss.",
"Chuck Norris can solo the Lich King. With fishing gear.",
"Chuck Norris doesn’t stealth. The world just looks the other way.",
"The Burning Legion once tried to invade Azeroth. Chuck Norris was visiting. Now it’s just called 'The Legion.'",
"Chuck Norris once played a game of Russian roulette with a fully loaded gun. He won.",
"Chuck Norris doesn't do quests. Quests complete themselves out of respect.",
"When Chuck Norris enters a battleground, the opposite team gets a debuff: Fear for eternity.",
"Chuck Norris can win a pet battle without any pets. Just his stare.",
"Chuck Norris once entered the Twisting Nether. Now it’s just called 'Straightened.'",
"Chuck Norris threw a grenade and killed 50 people. Then it exploded.",
"Chuck Norris can unlearn a profession by intimidating it.",
"Chuck Norris doesn’t need to capture flags in battlegrounds. The flags capture themselves for him.",
"The Cataclysm was actually caused by Chuck Norris getting angry at a goblin.",
"Chuck Norris once did a 'kill 10 rats' quest. Now Azeroth has no rats.",
"When Chuck Norris logs into WoW, the server population increases by one, but the server itself logs off in fear.",
"Chuck Norris can crit with a healing spell.",
"Chuck Norris completed all WoW achievements. On his trial account.",
"Deathwing didn’t destroy Azeroth. He just heard Chuck Norris was coming for him.",
"Chuck Norris doesn’t use a hearthstone. He stares at the innkeeper until he’s home.",
"LFM for Deadmines, need tank and healer, lvl 18-22 preferred.",
"LFG Zul'Farrak, lvl 44 mage here, can bring food and portals.",
"LF2M Uldaman, need DPS and a healer, lvl 35-40.",
"Tank LFG for Blackfathom Deeps, lvl 20-24.",
"Healer LFG Scarlet Monastery, any wing, lvl 30-40.",
"LF1M Tank for Scholomance, full run, lvl 58-60.",
"DPS LFG Maraudon, Princess run, lvl 45-50.",
"LF3M Stratholme, need healer and DPS, lvl 55-60.",
"LFG Shadowfang Keep, lvl 18-25, any role.",
"LFM for Dire Maul East, need DPS and healer, lvl 55-60.",
"Rogue LFG Razorfen Downs, can lockpick, lvl 35-40.",
"LF2M for Gnomeregan, need tank and healer, lvl 25-30.",
"Warrior tank LFG Blackrock Depths, full clear, lvl 52-56.",
"LFM Sunken Temple, need all roles, lvl 45-50.",
"LF1M healer for Lower Blackrock Spire, lvl 55-60.",
"LFG to farm Scarlet Monastery for xp and gear, lvl 30-40.",
"DPS LFG for Wailing Caverns, lvl 15-20.",
"LF2M DPS for The Stockade, quick xp, lvl 20-30.",
"LFM UBRS, need DPS and healer, key holder here, lvl 55-60.",
"LFG RFK, lvl 25-30, any role.",
"LF1M DPS for Molten Core attunement run through BRD, lvl 55-60.",
"LFM Naxxramas, JK, just need a group for RFD, lvl 35-40.",
"LF3M DPS for Maraudon purple run, lvl 40-45.",
"Tank LFG BRD arena/angerforge runs, lvl 52-56.",
"LFG for any part of Scarlet Monastery, lvl 30-40, DPS here.",
"LF2M for Shadowfang Keep, quick run, lvl 15-25.",
"Healer LFG Uldaman, have quest, lvl 35-40.",
"LFM for Zul'Farrak, zombies run, lvl 42-46.",
"LFG BFD, lvl 20-24, any role but DPS preferred.",
"LF1M healer for Dire Maul West, doing tribute run, lvl 55-60.",
{"Who's the worst dude to have in your raid??",
"The worst is definitely the guy who AFKs right before the boss pull.",
"Nothing beats the healer who forgets to heal because they're too busy chatting.",
"How about DPS who can't stay out of the fire? Literally, just move.",
"The one who always pulls extra mobs because they weren't paying attention.",
"Anyone who ninja loots. They ruin the raid for everyone.",
"The raid leader who yells but doesn't explain tactics.",
"People who don't bring any consumables and expect to be carried.",
"The player who constantly dies to avoidable mechanics. Every. Single. Time.",
"That person who always blames the tank for their own mistakes.",
"The one who thinks they know everything but keeps messing up mechanics.",
"DPS who think they're the tank and keep pulling ahead.",
"The one who's always arguing with the raid leader's strategies.",
"Anyone who bails after one wipe. Like, do they expect perfection?",
"The player who spends the whole raid hitting on other guild members.",
"Healers who are actually DPS spec and refuse to switch.",
"The guy who's always on follow because they're too lazy to move themselves.",
"Raiders who use the raid to vent about their personal life. Wrong place, man.",
"People who constantly whisper the raid leader about loot during encounters.",
"The person who always forgets to repair and breaks gear mid-raid.",
"Anyone who loudly eats into their mic without realizing it's on.",
"The one who insists on explaining every fight, even though we've all done it 100 times.",
"DPS who ignore add control and just tunnel vision the boss.",
"Players who join the raid then immediately ask for a summon.",
"The one who lies about having experience with the raid to get invited.",
"That player who's always asking for mana breaks. We just started!",
"Someone who refuses to download and use required addons.",
"The player who always has to leave early, right before the final boss.",
"Raiders who bring their alt with no gear and expect to be carried.",
"Anyone who's more focused on parsing than on following the strategy.",
"The guy who invites his clueless friend without asking the raid leader."},
"Everybody gangsta til the murlocs start healing eachother",
"muricans arguing about pizza never tasted an actual one from a stone oven",
"imagine sucking at a game you've been playing for 20+ years",
"LFM BRD, doing jailbreak!",
"LFM Onyxia attunement! Starting fresh!",
"LFG BRD Lava run!",
"Did you guys know there's a custom solo Hallow's End event in Raven Hill? Super fun and has an awesome transmog reward too! Reminds me of Legion's mage towers.",
"These new tier 1 and tier 2 set bonuses for offspecs are nice...wonder when Dinkle will finish AQ and T3 sets. I like that he put the vendors right outside MC and BWL too.",
{"Hey, I just got something super cool from this Inconspicuous chest! I thought these things only dropped Reward Points and gold.", "Nope, they also have a chance to drop quite a few things from the old Trading Card game."},
{"How come the new boss in AQ, Kazzak or any of the new world bosses show up in Atlas Loot?", "Probably because Dinkle hasn't gotten around to it yet.", "Yeah, little incentive to update it these days now that we have an online database."},
{"I can't seem to find certain trainers where they're supposed to be. Does anyone know?", "Yeah, trainers follow vanilla progression. So Master Enchanter for Alliance is in Uldaman, for example."} ,
{"Anyone know when Dinkle will start working on TBC?", "Probably when he's done with Grim Batol and Emerald Dream. He has a few other plans for vanilla too but the dude's busy so it may take awhile.", "Yeah, he seems excited to start work on tbc, but also tries to work on projects that excite him. I'm glad he does because then the quality will be better."},
{"Does Dinkle plan on adding a rune system like Ascension or Classic WoW?", "Nah, he likes the wotlk talent system. He does think it might be cool to extend glyphs though at some point. Just requires quite a bit of custom UI work."},
{"Uh, where do I go to for class quests if I don't have a trainer for my particular race?", "Any class trainer. They should work for all races. This means that you may get some quests twice but that's just an easy way to circumvent the race issue. Dinkle will get around to custom race class trainers at some point."},
{"Anyone know when we'll be able to do more BGs than just the first three?", "You'd have to ask Trickerer. He's the head honcho when it comes to bot development. Dinkle just tinkers with bot code and doesn't want to get bogged down with major bot development."},
{"Are there any plans for Uldum, Hyjal, etc?", "Yeah once the team gets done with Gilneas they'll do more stuff there. They're planning on a lot of those cata zones being sideways content to TBC."},
{"Do leveling challenges give any sort of rewards?", "Yes. Some even give very good permanent bonuses to your character."},

}

return text

